config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_scope :admin do
    get 'admin/login', to: 'devise/sessions#new', as: 'new_login'
    post 'admin/login', to: 'devise/sessions#create', as: 'login'
    get 'admin/logout', to: 'devise/sessions#destroy', as: 'logout'
    get 'admin/edit', to: 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admin/edit', to: 'registrations#update', as: 'admin_registration'
    # get 'admin/registration', to: 'devise/registrations#new', as: 'new_registration'
    # post 'admin/registration', to: 'devise/registrations#create', as: 'registration'
  end
   devise_for :admins #, skip: [:sessions, :registrations, :passwords]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'map#index'

  get 'about', to: 'about#index'

  get 'findme', to: 'map#index'

  get 'admin', to: 'admin#index'

  namespace :admin do
    resources :buildings, except: [:show]
    resources :rooms, except: [:show]
    resources :admins, except: [:show]
    resources :points, except: [:show]
    resources :plans, except: [:show]
  end

  namespace :map do
    namespace :search do
      get '/', action: 'search'
      get '/geo', action: 'search_geo'
    end

    namespace :data do
      get 'buildings', action: 'buildings'
      get 'building/:id', action: 'building'
      get 'room/:id', action: 'room', as: :room
      get 'rooms/:building_id', action: 'rooms'
      get 'bikes', action: 'bikes'
      get 'bathrooms', action: 'bathrooms'
      get 'snackbars', action: 'snackbars'
      get 'busstops', action: 'busstops'
      get 'entrances', action: 'entrances'
      get 'informationpoints', action: 'informationpoints'
    end
  end

  get 'map/data'
  get 'map/building/:id', to: 'map#building'
  get 'map/routes'

  #This route run the parse for catch the data of buildings and rooms of matriculaweb page
  #get 'parse', to: 'parser#index'

  get 'map/datapoint'
  get 'map/point/:id', to: 'map#point'

  get 'map/routes'
  get 'map/building'

  get 'map/point'

  # Provisory method to destroy points and buildings
  get 'admin/points/:id', to: 'admin/points#destroy'
  get 'admin/buildings/:id', to: 'admin/buildings#destroy'
end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-default" id="navbar">
    <div class="navbar-collapse collapse in">
        <ul class="nav navbar-nav navbar-mobile">
            <li>
                <button type="button" class="sidebar-toggle">
                    <i class="fa fa-bars"></i>
                </button>
            </li>
            <li class="logo">
                <a class="navbar-brand" href="#">
                    <span class="highlight">Onde É</span>
                    UnB</a>
            </li>
            <li>
                <button type="button" class="navbar-toggle">
                    <%= image_tag 'avatar' , class: 'profile-img' %>
                </button>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-left">
            <li class="navbar-title">Painel de Administração</li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown profile">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">
                    <%= image_tag 'avatar.png', class: 'profile-img' %>
                    <div class="title">Profile</div>
                </a>
                <div class="dropdown-menu">
                    <div class="profile-info">
                        <h4 class="username"><%= current_admin.name %></h4>
                    </div>
                    <ul class="action">
                        <li>
                            <%= link_to 'Configurações', edit_admin_registration_path  %>
                        </li>
                        <li>
                            <%= link_to 'Sair', logout_path  %>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<aside class="app-sidebar" id="sidebar">
    <div class="sidebar-header">
        <a class="sidebar-brand" href="<%= root_path %>">
            <span class="highlight">Onde É</span>
            UnB</a>
        <button type="button" class="sidebar-toggle">
            <i class="fa fa-times"></i>
        </button>
    </div>
    <div class="sidebar-menu">
        <ul class="sidebar-nav">
            <li>
                <a href="<%= admin_buildings_path %>">
                    <div class="icon">
                        <i class="fa fa-building" aria-hidden="true"></i>
                    </div>
                    <div class="title">Edifícios</div>
                </a>
            </li>
            <li>
                <a href="<%= admin_rooms_path %>">
                    <div class="icon">
                        <i class="fa fa-building" aria-hidden="true"></i>
                    </div>
                    <div class="title">Salas</div>
                </a>
            </li>
            <li>
                <a href="<%= admin_points_path %>">
                    <div class="icon">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                    </div>
                    <div class="title">Pontos</div>
                </a>
            </li>
            <li>
                <a href="<%= admin_plans_path %>">
                    <div class="icon">
                        <i class="fa fa-map" aria-hidden="true"></i>
                    </div>
                    <div class="title">Plantas</div>
                </a>
            </li>
            <li>
                <a href="<%= admin_admins_path %>">
                    <div class="icon">
                        <i class="fa fa-id-card" aria-hidden="true"></i>
                    </div>
                    <div class="title">Administradores</div>
                </a>
            </li>
        </ul>
    </div>
</aside>