config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_scope :admin do
    get 'admin/login', to: 'devise/sessions#new', as: 'new_login'
    post 'admin/login', to: 'devise/sessions#create', as: 'login'
    get 'admin/logout', to: 'devise/sessions#destroy', as: 'logout'
    get 'admin/edit', to: 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admin/edit', to: 'registrations#update', as: 'admin_registration'
    # get 'admin/registration', to: 'devise/registrations#new', as: 'new_registration'
    # post 'admin/registration', to: 'devise/registrations#create', as: 'registration'
  end
   devise_for :admins #, skip: [:sessions, :registrations, :passwords]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'map#index'

  get 'about', to: 'about#index'

  get 'findme', to: 'map#index'

  get 'admin', to: 'admin#index'

  namespace :admin do
    resources :buildings, except: [:show]
    resources :rooms, except: [:show]
    resources :admins, except: [:show]
    resources :points, except: [:show]
    resources :plans, except: [:show]
  end

  namespace :map do
    namespace :search do
      get '/', action: 'search'
      get '/geo', action: 'search_geo'
    end

    namespace :data do
      get 'buildings', action: 'buildings'
      get 'building/:id', action: 'building'
      get 'room/:id', action: 'room', as: :room
      get 'rooms/:building_id', action: 'rooms'
      get 'bikes', action: 'bikes'
      get 'bathrooms', action: 'bathrooms'
      get 'snackbars', action: 'snackbars'
      get 'busstops', action: 'busstops'
      get 'entrances', action: 'entrances'
      get 'informationpoints', action: 'informationpoints'
    end
  end

  get 'map/data'
  get 'map/building/:id', to: 'map#building'
  get 'map/routes'

  #This route run the parse for catch the data of buildings and rooms of matriculaweb page
  #get 'parse', to: 'parser#index'

  get 'map/datapoint'
  get 'map/point/:id', to: 'map#point'

  get 'map/routes'
  get 'map/building'

  get 'map/point'

  # Provisory method to destroy points and buildings
  get 'admin/points/:id', to: 'admin/points#destroy'
  get 'admin/buildings/:id', to: 'admin/buildings#destroy'
end

app/models/point.rb
class Point < ApplicationRecord
      acts_as :location
      enum type_point: ["Bicicletario", "Banheiro", "Lanchonete", "Parada de Onibus", "Entrada de Edificio", "Ponto de Informacao"]
      validates :type_point, presence: true
      validates :description, length: { maximum: 200}, presence: true
      validates :title, length: { maximum: 50 }, presence: true
      validates :latitude, numericality: true, presence: true
      validates :longitude, numericality: true, presence: true
      validates :geo_data, presence: true
end

app/controllers/admin/points_controller.rb
class Admin::PointsController < AdminController
  before_action :set_point, only: [:destroy, :edit, :update]

  def index
    @points = Point.order("type_point").page(params['page']).per(13)
  end

  def new
    @point = Point.new
  end

  def edit
  end

  def update
    if @point.update(point_params)
      redirect_to admin_points_path, notice: alert_success('Ponto editado com êxito.')
    else
      render :edit
    end
  end

  def create
    @point = Point.new(point_params)
    if @point.save
      redirect_to admin_points_path, notice: alert_success('Ponto criado com êxito.')
    else
      render :new
    end
  end

  def destroy
    @point.destroy
    redirect_to admin_points_path, notice: alert_success('Ponto excluído com êxito.')
  end

  private

  def alert_success(message)
    "<div class='alert alert-success'>#{message}</div>"
  end

  def alert_danger(message)
    "<div class='alert alert-danger'>#{message}</div>"
  end

  def set_point
    @point = Point.find(params[:id])
  end

  def point_params
    params.require(:point).permit(:title, :type_point, :description, :latitude, :longitude, :geo_data)
  end
end

app/views/admin/points/_form.html.erb
<div  id="card" class="card">
    <div class="row">
        <div class="col-md-5">
            <div class="card-header">
                <%= title %>
            </div>
            <div class="card-body">
                <%= form_for(point, url: url, validate: true) do |f| %>
                <div class="row">
                    <div class="form-group col-md-6">
                        <%= f.label "Título" %>
                        <%= f.text_field :title, class: 'form-control' %>
                    </div>
                    <div class="form-group col-md-6">
                        <%= f.label "Tipo de Ponto" %>
                        <%= f.select :type_point, ['Bicicletario', 'Banheiro','Lanchonete', 'Parada de Onibus', 'Entrada de Edificio', 'Ponto de Informacao'], {}, {required: 'true', class: 'form-control' } %>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <%= f.label "Descrição" %>
                        <%= f.text_field :description, class: 'form-control' %>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <%= f.label :latitude %>
                        <%= f.text_field :latitude, class: 'form-control' %>
                    </div>
                    <div class="form-group col-md-6">
                        <%= f.label :longitude %>
                        <%= f.text_field :longitude, class: 'form-control' %>
                    </div>
                </div>
                <div class="form-group">
                    <%= f.hidden_field :geo_data %>
                    <%= f.submit 'Salvar', class: 'btn btn-sm btn-success', id: "Salvar" %>
                </div>
                <% end %>
            </div>
        </div>
        <div class="col-md-7">
            <div id="map" style="float: left;"></div>
        </div>
    </div>
</div>

app/views/admin/points/edit.html.erb
<%= render 'form', title: 'Editar Ponto', point: @point, url: admin_point_path(@point) %>

app/views/admin/points/index.html.erb
<div class="row" style="margin-top: 30px;">
    <div class="col-xs-12">
      <%= notice.html_safe unless notice.blank? %>
        <div class="card card-mini">
            <div class="card-header">
                <div class="card-title">Pontos</div>
                <ul class="card-action">
                    <li>
                        <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_admin_point_path %>
                    </li>
                </ul>
            </div>
            <div class="card-body no-padding table-responsive">
                <table class="table card-table">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Tipo</th>
                            <th>Descrição</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @points.each do |point| %>
                        <tr>
                            <td><%= point.title %></td>
                            <td><%= point.type_point %></td>
                            <td><%= point.description %></td>
                            <td>
                                <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_admin_point_path(point) %>
                                <%= link_to '<i class="fa fa-remove"></i>'.html_safe, admin_point_path(point), method: :delete, data: {
                                  'sweet-alert-confirm': 'Alerta',
                                  'confirm-button-text': 'Sim',
                                  'confirm-button-color': '#DD6B55',
                                  'cancel-button-text': 'Cancelar',
                                  'text': 'Tem certeza que deseja apagar este ponto?'
                                } %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <%= paginate @points, window: 3 %>
            </div>
        </div>
    </div>
</div>

app/views/admin/points/new.html.erb
<%= render 'form', title: 'Criar Ponto', point: @point, url: admin_points_path %>