config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  devise_scope :admin do
    get 'admin/login', to: 'devise/sessions#new', as: 'new_login'
    post 'admin/login', to: 'devise/sessions#create', as: 'login'
    get 'admin/logout', to: 'devise/sessions#destroy', as: 'logout'
    get 'admin/edit', to: 'devise/registrations#edit', as: 'edit_admin_registration'
    put 'admin/edit', to: 'registrations#update', as: 'admin_registration'
    # get 'admin/registration', to: 'devise/registrations#new', as: 'new_registration'
    # post 'admin/registration', to: 'devise/registrations#create', as: 'registration'
  end
   devise_for :admins #, skip: [:sessions, :registrations, :passwords]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'map#index'

  get 'about', to: 'about#index'

  get 'findme', to: 'map#index'

  get 'admin', to: 'admin#index'

  namespace :admin do
    resources :buildings, except: [:show]
    resources :rooms, except: [:show]
    resources :admins, except: [:show]
    resources :points, except: [:show]
    resources :plans, except: [:show]
  end

  namespace :map do
    namespace :search do
      get '/', action: 'search'
      get '/geo', action: 'search_geo'
    end

    namespace :data do
      get 'buildings', action: 'buildings'
      get 'building/:id', action: 'building'
      get 'room/:id', action: 'room', as: :room
      get 'rooms/:building_id', action: 'rooms'
      get 'bikes', action: 'bikes'
      get 'bathrooms', action: 'bathrooms'
      get 'snackbars', action: 'snackbars'
      get 'busstops', action: 'busstops'
      get 'entrances', action: 'entrances'
      get 'informationpoints', action: 'informationpoints'
    end
  end

  get 'map/data'
  get 'map/building/:id', to: 'map#building'
  get 'map/routes'

  #This route run the parse for catch the data of buildings and rooms of matriculaweb page
  #get 'parse', to: 'parser#index'

  get 'map/datapoint'
  get 'map/point/:id', to: 'map#point'

  get 'map/routes'
  get 'map/building'

  get 'map/point'

  # Provisory method to destroy points and buildings
  get 'admin/points/:id', to: 'admin/points#destroy'
  get 'admin/buildings/:id', to: 'admin/buildings#destroy'
end

app/models/plan.rb
class Plan < ApplicationRecord
  include PlanUploader[:image]
  belongs_to :building
  validates :building, presence: true
  validates :level, numericality: { only_integer: true }, presence: true
  validates :geo_data, presence: true
  validates :image, presence: true
end

app/controllers/admin/plans_controller.rb
class Admin::PlansController < AdminController
  before_action :set_plans, only: [:destroy, :edit, :update]
  before_action :set_buildings, only: [:new, :edit, :update, :create]

  def index
    @plans = Plan.order("building_id").page(params['page']).per(13)
  end

  def new
    @plan = Plan.new
  end

  def edit
  end

  def update
    if @plan.update(plans_params)
      redirect_to admin_plans_path, notice: helpers.alert_success('Planta editada com êxito.')
    else
      render :edit
    end
  end

  def create
    @plan = Plan.new(plans_params)
    if @plan.save
      redirect_to admin_plans_path, notice: helpers.alert_success('Planta cadastrada com êxito.')
    else
      render :new
    end
  end

  def destroy
    @plan.destroy
    redirect_to admin_plans_path, notice: helpers.alert_success('Planta excluída com êxito.')
  end

  private

  def set_buildings
    @buildings = Building.all
  end

  def set_plans
    @plan = Plan.find(params[:id])
  end

  def plans_params
    params.require(:plan).permit(:building_id, :level, :geo_data, :image)
  end
end

app/views/admin/plans/_form.html.erb
<div class="card">
  <div class="row">
    <div class="col-md-3">
      <div class="card-header">
        <%= title %>
      </div>
      <div class="card-body">
        <%= form_for(plan, url: url, validate: true) do |f| %>
        <div class="form-group">
          <%= f.label :building_id %>
          <%= f.select :building_id, options_from_collection_for_select(@buildings, :id, :acronym), {}, { class: 'form-control' } %>
        </div>
        <div class="form-group">
          <%= f.label :level %>
          <%= f.number_field :level, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.hidden_field :image, value: plan.cached_image_data, data: { image: plan.image_url } %>
          <%= f.file_field :image, class: 'form-control plan_image_file'%>
        </div>
        <div class="form-group">
          <%= f.hidden_field :geo_data %>
          <%= f.submit 'Salvar', class: 'btn btn-sm btn-success', id: "Salvar"  %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-9">
      <div id="map"></div>
    </div>
  </div>
</div>

app/views/admin/plans/edit.html.erb
<%= render 'form', title: 'Editar Planta', plan: @plan, url: admin_plan_path(@plan) %>

app/views/admin/plans/index.html.erb
<div class="row" style="margin-top: 30px;">
    <div class="col-xs-12">
      <%= notice.html_safe unless notice.blank? %>
        <div class="card card-mini">
            <div class="card-header">
                <div class="card-title">Plantas</div>
                <ul class="card-action">
                    <li>
                        <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_admin_plan_path %>
                    </li>
                </ul>
            </div>
            <div class="card-body no-padding table-responsive">
                <table class="table card-table">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Andar</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @plans.each do |plan| %>
                        <tr>
                            <td><%= plan.building.title %></td>
                            <td><%= plan.level %></td>
                            <td>
                                <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_admin_plan_path(plan) %>
                                <%= link_to '<i class="fa fa-remove"></i>'.html_safe, admin_plan_path(plan), method: :delete, data: {
                                  confirm: 'Are you ready?',
                                  'sweet-alert-confirm': 'Alerta',
                                  'confirm-button-text': 'Sim',
                                  'confirm-button-color': '#DD6B55',
                                  'cancel-button-text': 'Cancelar',
                                  'text': 'Tem certeza que deseja apagar esta planta?'
                                } %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <%= paginate @plans, window: 3 %>
            </div>
        </div>
    </div>
</div>

app/views/admin/plans/new.html.erb
<%= render 'form', title: 'Criar Planta', plan: @plan, url: admin_plans_path %>